// Automatically generated by xmlvm2csharp (do not edit).

using global::org.xmlvm;
using global::java = global::org.xmlvm.java;
namespace Compatlib.System.Windows.Input {
public class ManipulationCompletedEventArgs: global::Compatlib.System.Windows.Input.InputEventArgs {
private global::Compatlib.System.Windows.Point _fManipulationOrigin;

public new void @this(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Input.ManipulationCompletedEventArgs: void <init>()]
    global::org.xmlvm._nElement _r0;
    _r0.i = 0;
    _r0.l = 0;
    _r0.f = 0;
    _r0.d = 0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r0_o = this;
    ((global::Compatlib.System.Windows.Input.InputEventArgs) _r0_o).@this();
    return;
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Input.ManipulationCompletedEventArgs: void <init>()]
}

public virtual global::System.Object getManipulationOrigin(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Input.ManipulationCompletedEventArgs: Compatlib.System.Windows.Point getManipulationOrigin()]
    global::org.xmlvm._nElement _r0;
    _r0.i = 0;
    _r0.l = 0;
    _r0.f = 0;
    _r0.d = 0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    _r1.i = 0;
    _r1.l = 0;
    _r1.f = 0;
    _r1.d = 0;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r1_o = this;
    _r0_o = ((global::Compatlib.System.Windows.Input.ManipulationCompletedEventArgs) _r1_o)._fManipulationOrigin;
    return (global::Compatlib.System.Windows.Point) _r0_o;
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Input.ManipulationCompletedEventArgs: Compatlib.System.Windows.Point getManipulationOrigin()]
}

public virtual void setManipulationOrigin(global::Compatlib.System.Windows.Point n1){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Input.ManipulationCompletedEventArgs: void setManipulationOrigin(Compatlib.System.Windows.Point)]
    global::org.xmlvm._nElement _r0;
    _r0.i = 0;
    _r0.l = 0;
    _r0.f = 0;
    _r0.d = 0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    _r1.i = 0;
    _r1.l = 0;
    _r1.f = 0;
    _r1.d = 0;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r0_o = this;
    _r1_o = n1;
    ((global::Compatlib.System.Windows.Input.ManipulationCompletedEventArgs) _r0_o)._fManipulationOrigin = (global::Compatlib.System.Windows.Point) _r1_o;
    return;
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Input.ManipulationCompletedEventArgs: void setManipulationOrigin(Compatlib.System.Windows.Point)]
}

//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Input.ManipulationCompletedEventArgs]
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Input.ManipulationCompletedEventArgs]

} // end of class: ManipulationCompletedEventArgs

} // end of namespace: Compatlib.System.Windows.Input
