// Automatically generated by xmlvm2csharp (do not edit).

using global::org.xmlvm;
using global::java = global::org.xmlvm.java;
namespace Compatlib.System.Windows.Input {
public class ManipulationDelta: global::java.lang.Object {
private global::Compatlib.System.Windows.Vector _fTranslation;

public new void @this(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Input.ManipulationDelta: void <init>()]
    global::org.xmlvm._nElement _r0;
    _r0.i = 0;
    _r0.l = 0;
    _r0.f = 0;
    _r0.d = 0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r0_o = this;
    ((global::java.lang.Object) _r0_o).@this();
    return;
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Input.ManipulationDelta: void <init>()]
}

public virtual global::System.Object getTranslation(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Input.ManipulationDelta: Compatlib.System.Windows.Vector getTranslation()]
    global::org.xmlvm._nElement _r0;
    _r0.i = 0;
    _r0.l = 0;
    _r0.f = 0;
    _r0.d = 0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    _r1.i = 0;
    _r1.l = 0;
    _r1.f = 0;
    _r1.d = 0;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r1_o = this;
    _r0_o = ((global::Compatlib.System.Windows.Input.ManipulationDelta) _r1_o)._fTranslation;
    return (global::Compatlib.System.Windows.Vector) _r0_o;
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Input.ManipulationDelta: Compatlib.System.Windows.Vector getTranslation()]
}

public virtual void setTranslation(global::Compatlib.System.Windows.Vector n1){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Input.ManipulationDelta: void setTranslation(Compatlib.System.Windows.Vector)]
    global::org.xmlvm._nElement _r0;
    _r0.i = 0;
    _r0.l = 0;
    _r0.f = 0;
    _r0.d = 0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    _r1.i = 0;
    _r1.l = 0;
    _r1.f = 0;
    _r1.d = 0;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r0_o = this;
    _r1_o = n1;
    ((global::Compatlib.System.Windows.Input.ManipulationDelta) _r0_o)._fTranslation = (global::Compatlib.System.Windows.Vector) _r1_o;
    return;
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Input.ManipulationDelta: void setTranslation(Compatlib.System.Windows.Vector)]
}

//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Input.ManipulationDelta]
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Input.ManipulationDelta]

} // end of class: ManipulationDelta

} // end of namespace: Compatlib.System.Windows.Input
