
// Automatically generated by xmlvm2csharp. Do not edit!

using org.xmlvm;
using java = org.xmlvm.java;
namespace Compatlib.System.Windows.Input {
public class Touch: Compatlib.System.Object {

static Touch() {
    @static();
}

public static Compatlib.System.Windows.Input.FrameReportedEvent FrameReported;

public static new void @static(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Input.Touch: void <clinit>()]
    FrameReported = new FrameReportedEvent();
    FrameReported.@this();

    global::System.Windows.Input.Touch.FrameReported += FrameReportedHandler;
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Input.Touch: void <clinit>()]
}

public new void @this(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Input.Touch: void <init>()]
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Input.Touch: void <init>()]
}

//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Input.Touch]
static void FrameReportedHandler(object sender, global::System.Windows.Input.TouchFrameEventArgs args)
{
    Compatlib.System.Windows.Input.TouchFrameEventArgs newArgs = new Compatlib.System.Windows.Input.TouchFrameEventArgs();
    newArgs.args = args;
    FrameReported.__fire(null, newArgs);
}
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Input.Touch]

} // end of class: Touch

} // end of namespace: Compatlib.System.Windows.Input
