// Automatically generated by xmlvm2csharp (do not edit).

using global::org.xmlvm;
using global::java = global::org.xmlvm.java;
namespace Compatlib.System.Windows.Input {
public class ManipulationDeltaEventArgs: global::Compatlib.System.Windows.Input.InputEventArgs {
private global::Compatlib.System.Windows.Input.ManipulationDelta _fDeltaManipulation;

public new void @this(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Input.ManipulationDeltaEventArgs: void <init>()]
    global::org.xmlvm._nElement _r0;
    _r0.i = 0;
    _r0.l = 0;
    _r0.f = 0;
    _r0.d = 0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r0_o = this;
    ((global::Compatlib.System.Windows.Input.InputEventArgs) _r0_o).@this();
    return;
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Input.ManipulationDeltaEventArgs: void <init>()]
}

public virtual global::System.Object getDeltaManipulation(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Input.ManipulationDeltaEventArgs: Compatlib.System.Windows.Input.ManipulationDelta getDeltaManipulation()]
    global::org.xmlvm._nElement _r0;
    _r0.i = 0;
    _r0.l = 0;
    _r0.f = 0;
    _r0.d = 0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    _r1.i = 0;
    _r1.l = 0;
    _r1.f = 0;
    _r1.d = 0;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r1_o = this;
    _r0_o = ((global::Compatlib.System.Windows.Input.ManipulationDeltaEventArgs) _r1_o)._fDeltaManipulation;
    return (global::Compatlib.System.Windows.Input.ManipulationDelta) _r0_o;
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Input.ManipulationDeltaEventArgs: Compatlib.System.Windows.Input.ManipulationDelta getDeltaManipulation()]
}

public virtual void setDeltaManipulation(global::Compatlib.System.Windows.Input.ManipulationDelta n1){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Input.ManipulationDeltaEventArgs: void setDeltaManipulation(Compatlib.System.Windows.Input.ManipulationDelta)]
    global::org.xmlvm._nElement _r0;
    _r0.i = 0;
    _r0.l = 0;
    _r0.f = 0;
    _r0.d = 0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    _r1.i = 0;
    _r1.l = 0;
    _r1.f = 0;
    _r1.d = 0;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r0_o = this;
    _r1_o = n1;
    ((global::Compatlib.System.Windows.Input.ManipulationDeltaEventArgs) _r0_o)._fDeltaManipulation = (global::Compatlib.System.Windows.Input.ManipulationDelta) _r1_o;
    return;
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Input.ManipulationDeltaEventArgs: void setDeltaManipulation(Compatlib.System.Windows.Input.ManipulationDelta)]
}

//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Input.ManipulationDeltaEventArgs]
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Input.ManipulationDeltaEventArgs]

} // end of class: ManipulationDeltaEventArgs

} // end of namespace: Compatlib.System.Windows.Input
