
// Automatically generated by xmlvm2csharp. Do not edit!

using org.xmlvm;
using java = org.xmlvm.java;
namespace Compatlib.System.Windows.Input {
public class TouchAction: Compatlib.System.Object {

static TouchAction() {
    @static();
}

public static Compatlib.System.Windows.Input.TouchAction Down;

public static new void @static(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Input.TouchAction: void <clinit>()]
    Down = new TouchAction();
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Input.TouchAction: void <clinit>()]
}

public new void @this(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Input.TouchAction: void <init>()]
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Input.TouchAction: void <init>()]
}

//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Input.TouchAction]
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Input.TouchAction]

} // end of class: TouchAction

} // end of namespace: Compatlib.System.Windows.Input
