
// Automatically generated by xmlvm2csharp. Do not edit!

using org.xmlvm;
using java = org.xmlvm.java;
namespace Compatlib.System.Windows.Controls.Primitives {
public class ButtonBase: Compatlib.System.Windows.Controls.ContentControl {
public Compatlib.System.Windows.Controls.Primitives.ClickEvent Click;

public new void @this(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Controls.Primitives.ButtonBase: void <init>()]
    this.Click = new ClickEvent();
    this.Click.@this();

    ((global::System.Windows.Controls.Primitives.ButtonBase)base.element).Click += ClickHandler;
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Controls.Primitives.ButtonBase: void <init>()]
}

//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Controls.Primitives.ButtonBase]
public void ClickHandler(object sender, global::System.Windows.RoutedEventArgs args)
{
    Compatlib.System.Windows.RoutedEventArgs newArgs = new Compatlib.System.Windows.RoutedEventArgs();
    newArgs.args = args;
    this.Click.__fire(this, newArgs);
}
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Controls.Primitives.ButtonBase]

} // end of class: ButtonBase

} // end of namespace: Compatlib.System.Windows.Controls.Primitives
