
// Automatically generated by xmlvm2csharp. Do not edit!

using org.xmlvm;
using java = org.xmlvm.java;
namespace Compatlib.System.Windows.Controls {
public class UIElementCollection: Compatlib.System.Windows.Controls.PresentationFrameworkCollection {
public new void @this(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Controls.UIElementCollection: void <init>()]
    base.@this();
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Controls.UIElementCollection: void <init>()]
}

public virtual void Add(Compatlib.System.Windows.UIElement n1){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Controls.UIElementCollection: void Add(Compatlib.System.Windows.UIElement)]
    collection.Add(n1.element);
    base.Add(n1);
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Controls.UIElementCollection: void Add(Compatlib.System.Windows.UIElement)]
}

public override void Add(java.lang.Object n1){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Controls.UIElementCollection: void Add(java.lang.Object)]
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Controls.UIElementCollection: void Add(java.lang.Object)]
}

//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Controls.UIElementCollection]
public global::System.Windows.Controls.UIElementCollection collection;
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Controls.UIElementCollection]

} // end of class: UIElementCollection

} // end of namespace: Compatlib.System.Windows.Controls
