// Automatically generated by xmlvm2csharp (do not edit).

using org.xmlvm;
namespace java.util {
public class Locale: java.lang.Object,java.lang.Cloneable,java.io.Serializable {
private static void initNativeLayer(){
//XMLVM_BEGIN_WRAPPER[java.util.Locale: void initNativeLayer()]
      throw new org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.util.Locale: void initNativeLayer()]
}

//XMLVM_BEGIN_WRAPPER[java.util.Locale]
//XMLVM_END_WRAPPER[java.util.Locale]

} // end of class: Locale

} // end of namespace: java.util
