
// Automatically generated by xmlvm2csharp. Do not edit!

using org.xmlvm;
using java = org.xmlvm.java;
namespace Compatlib.System.Collections.Generics {
public interface ICollection {
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Collections.Generics.ICollection]
//XMLVM_END_WRAPPER[Compatlib.System.Collections.Generics.ICollection]

} // end of class: ICollection

} // end of namespace: Compatlib.System.Collections.Generics
