
// Automatically generated by xmlvm2csharp. Do not edit!

using org.xmlvm;
using java = org.xmlvm.java;
namespace Compatlib.System.Collections.Generics {
public interface IEnumerator: Compatlib.System.IDisposable {
 java.lang.Object getCurrent();

 int MoveNext();

//XMLVM_BEGIN_WRAPPER[Compatlib.System.Collections.Generics.IEnumerator]
//XMLVM_END_WRAPPER[Compatlib.System.Collections.Generics.IEnumerator]

} // end of class: IEnumerator

} // end of namespace: Compatlib.System.Collections.Generics
