
// Automatically generated by xmlvm2csharp. Do not edit!

using org.xmlvm;
using java = org.xmlvm.java;
namespace Compatlib.System.Collections.Generics {
public interface IList {
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Collections.Generics.IList]
//XMLVM_END_WRAPPER[Compatlib.System.Collections.Generics.IList]

} // end of class: IList

} // end of namespace: Compatlib.System.Collections.Generics
