
// Automatically generated by xmlvm2csharp. Do not edit!

using org.xmlvm;
using java = org.xmlvm.java;
namespace Compatlib.System {
public interface IComparable {
//XMLVM_BEGIN_WRAPPER[Compatlib.System.IComparable]
//XMLVM_END_WRAPPER[Compatlib.System.IComparable]

} // end of class: IComparable

} // end of namespace: Compatlib.System
