
// Automatically generated by xmlvm2csharp. Do not edit!

using org.xmlvm;
using java = org.xmlvm.java;
namespace Compatlib.System {
public interface IConvertible {
//XMLVM_BEGIN_WRAPPER[Compatlib.System.IConvertible]
//XMLVM_END_WRAPPER[Compatlib.System.IConvertible]

} // end of class: IConvertible

} // end of namespace: Compatlib.System
