// Automatically generated by xmlvm2csharp. Do not edit!

using org.xmlvm;
using java = org.xmlvm.java;
namespace Compatlib.System {
public abstract class _iIConvertible {

} // end of abstract class: _iIConvertible

public interface IConvertible {
//XMLVM_BEGIN_WRAPPER[Compatlib.System.IConvertible]
//XMLVM_END_WRAPPER[Compatlib.System.IConvertible]

} // end of interface: IConvertible

} // end of namespace: Compatlib.System
