
// Automatically generated by xmlvm2csharp. Do not edit!

using org.xmlvm;
using java = org.xmlvm.java;
namespace Compatlib.System {
public interface IDisposable {
//XMLVM_BEGIN_WRAPPER[Compatlib.System.IDisposable]
//XMLVM_END_WRAPPER[Compatlib.System.IDisposable]

} // end of class: IDisposable

} // end of namespace: Compatlib.System
