
// Automatically generated by xmlvm2csharp. Do not edit!

using org.xmlvm;
using java = org.xmlvm.java;
namespace Compatlib.System {
public interface IFormattable {
//XMLVM_BEGIN_WRAPPER[Compatlib.System.IFormattable]
//XMLVM_END_WRAPPER[Compatlib.System.IFormattable]

} // end of class: IFormattable

} // end of namespace: Compatlib.System
