
// Automatically generated by xmlvm2csharp. Do not edit!

using org.xmlvm;
using java = org.xmlvm.java;
namespace Compatlib.System {
public class Object: java.lang.Object {
public new void @this(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Object: void <init>()]
//XMLVM_END_WRAPPER[Compatlib.System.Object: void <init>()]
}

public virtual Compatlib.System.String ToString(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Object: Compatlib.System.String ToString()]
    java.lang.String jst = new java.lang.String(base.ToString());
    Compatlib.System.String st = new Compatlib.System.String();
    st.@this(jst);
    return st;
//XMLVM_END_WRAPPER[Compatlib.System.Object: Compatlib.System.String ToString()]
}

//XMLVM_BEGIN_WRAPPER[Compatlib.System.Object]
//XMLVM_END_WRAPPER[Compatlib.System.Object]

} // end of class: Object

} // end of namespace: Compatlib.System
