// Automatically generated by xmlvm2csharp. Do not edit!

using org.xmlvm;
using java = org.xmlvm.java;
namespace Compatlib.System {
public class String: Compatlib.System.Object {

static String() {
    @static();
}

public java.lang.String _fvalue;

public static Compatlib.System.String _fEmpty;

public static new void @static(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.String: void <clinit>()]
//XMLVM_END_WRAPPER[Compatlib.System.String: void <clinit>()]
}

public void @this(java.lang.String n1){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.String: void <init>(java.lang.String)]
    this._fvalue = n1;
//XMLVM_END_WRAPPER[Compatlib.System.String: void <init>(java.lang.String)]
}

public override Compatlib.System.String ToString(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.String: Compatlib.System.String ToString()]
    return this;
//XMLVM_END_WRAPPER[Compatlib.System.String: Compatlib.System.String ToString()]
}

public override java.lang.String toString(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.String: java.lang.String toString()]
    return this._fvalue;
//XMLVM_END_WRAPPER[Compatlib.System.String: java.lang.String toString()]
}

public virtual bool Equals(Compatlib.System.String n1){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.String: boolean Equals(Compatlib.System.String)]
    return this.toString().equals(n1.toString());
//XMLVM_END_WRAPPER[Compatlib.System.String: boolean Equals(Compatlib.System.String)]
}

public virtual char _1_1access(int n1){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.String: char __access(int)]
    return this.toString().toCharArray().get(n1);
//XMLVM_END_WRAPPER[Compatlib.System.String: char __access(int)]
}

public virtual bool EndsWith(Compatlib.System.String n1){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.String: boolean EndsWith(Compatlib.System.String)]
    return org.xmlvm.Util.toNativeString(this.toString()).EndsWith(org.xmlvm.Util.toNativeString(n1.toString()));
//XMLVM_END_WRAPPER[Compatlib.System.String: boolean EndsWith(Compatlib.System.String)]
}

public virtual int getLength(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.String: int getLength()]
    return org.xmlvm.Util.toNativeString(this.toString()).Length;
//XMLVM_END_WRAPPER[Compatlib.System.String: int getLength()]
}

//XMLVM_BEGIN_WRAPPER[Compatlib.System.String]
//XMLVM_END_WRAPPER[Compatlib.System.String]

} // end of class: String

} // end of namespace: Compatlib.System
