
// Automatically generated by xmlvm2csharp. Do not edit!

using org.xmlvm;
using java = org.xmlvm.java;
namespace Compatlib.System {
public class Uri: Compatlib.System.Object {
public void @this(Compatlib.System.String n1, Compatlib.System.UriKind n2){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Uri: void <init>(Compatlib.System.String, Compatlib.System.UriKind)]
    uri = new global::System.Uri(n1.toString().ToString(), n2.uriKind);
//XMLVM_END_WRAPPER[Compatlib.System.Uri: void <init>(Compatlib.System.String, Compatlib.System.UriKind)]
}

//XMLVM_BEGIN_WRAPPER[Compatlib.System.Uri]
    public global::System.Uri uri;
//XMLVM_END_WRAPPER[Compatlib.System.Uri]

} // end of class: Uri

} // end of namespace: Compatlib.System
