// Automatically generated by xmlvm2csharp. Do not edit!

using org.xmlvm;
using java = org.xmlvm.java;
namespace org.xmlvm.java.lang {
public class Enum: org.xmlvm.java.lang.Object {
public void @this(org.xmlvm.java.lang.String n1, int n2){
//XMLVM_BEGIN_WRAPPER[org.xmlvm.java.lang.Enum: void <init>(org.xmlvm.java.lang.String, int)]
      throw new org.xmlvm.NotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[org.xmlvm.java.lang.Enum: void <init>(org.xmlvm.java.lang.String, int)]
}

//XMLVM_BEGIN_WRAPPER[org.xmlvm.java.lang.Enum]
//XMLVM_END_WRAPPER[org.xmlvm.java.lang.Enum]

} // end of class: Enum

} // end of namespace: org.xmlvm.java.lang
