
// Automatically generated by xmlvm2csharp. Do not edit!

using org.xmlvm;
using java = org.xmlvm.java;
namespace org.xmlvm.java.lang {
public class Math: java.lang.Object {
public new void @this(){
//XMLVM_BEGIN_WRAPPER[org.xmlvm.java.lang.Math: void <init>()]
//XMLVM_END_WRAPPER[org.xmlvm.java.lang.Math: void <init>()]
}

public static int max(int n1, int n2){
//XMLVM_BEGIN_WRAPPER[org.xmlvm.java.lang.Math: int max(int, int)]
return n1>n2 ? n1 : n2;
//XMLVM_END_WRAPPER[org.xmlvm.java.lang.Math: int max(int, int)]
}

public static int min(int n1, int n2){
//XMLVM_BEGIN_WRAPPER[org.xmlvm.java.lang.Math: int min(int, int)]
return n1>n2 ? n2 : n1;
//XMLVM_END_WRAPPER[org.xmlvm.java.lang.Math: int min(int, int)]
}

//XMLVM_BEGIN_WRAPPER[org.xmlvm.java.lang.Math]
//XMLVM_END_WRAPPER[org.xmlvm.java.lang.Math]

} // end of class: Math

} // end of namespace: org.xmlvm.java.lang
