// Automatically generated by xmlvm2csharp (Do not edit).

using org.xmlvm;
using java = org.xmlvm.java;
namespace org.xmlvm.java.lang {
public class Object {

static Object() {
    @static();
}

public void @this(){
//XMLVM_BEGIN_WRAPPER[org.xmlvm.java.lang.Object: void <init>()]
//XMLVM_END_WRAPPER[org.xmlvm.java.lang.Object: void <init>()]
}

public virtual global::System.Object toString(){
//XMLVM_BEGIN_WRAPPER[org.xmlvm.java.lang.Object: java.lang.String toString()]
throw new org.xmlvm._nNotYetImplementedException();
//XMLVM_END_WRAPPER[org.xmlvm.java.lang.Object: java.lang.String toString()]
}

public virtual bool equals(java.lang.Object n1){
//XMLVM_BEGIN_WRAPPER[org.xmlvm.java.lang.Object: boolean equals(java.lang.Object)]
if (this==n1) {
   return true;
} 
// else:
return false;
//XMLVM_END_WRAPPER[org.xmlvm.java.lang.Object: boolean equals(java.lang.Object)]
}

public virtual int hashCode(){
//XMLVM_BEGIN_WRAPPER[org.xmlvm.java.lang.Object: int hashCode()]
throw new org.xmlvm._nNotYetImplementedException();
//XMLVM_END_WRAPPER[org.xmlvm.java.lang.Object: int hashCode()]
}

public static void @static(){
//XMLVM_BEGIN_WRAPPER[org.xmlvm.java.lang.Object: void <clinit>()]
//XMLVM_END_WRAPPER[org.xmlvm.java.lang.Object: void <clinit>()]
}

//XMLVM_BEGIN_WRAPPER[org.xmlvm.java.lang.Object]
//XMLVM_END_WRAPPER[org.xmlvm.java.lang.Object]

} // end of class: Object

} // end of namespace: org.xmlvm.java.lang
