
// Automatically generated by xmlvm2csharp. Do not edit!

using org.xmlvm;
using java = org.xmlvm.java;
namespace org.xmlvm.java.lang {
public interface Runnable {
 void run();

//XMLVM_BEGIN_WRAPPER[org.xmlvm.java.lang.Runnable]
//XMLVM_END_WRAPPER[org.xmlvm.java.lang.Runnable]

} // end of class: Runnable

} // end of namespace: org.xmlvm.java.lang
