// Automatically generated by xmlvm2csharp. Do not edit!

using org.xmlvm;
using java = org.xmlvm.java;
namespace org.xmlvm.java.lang {
public class String: org.xmlvm.java.lang.Object {
public new void @this(){
//XMLVM_BEGIN_WRAPPER[org.xmlvm.java.lang.String: void <init>()]
      throw new org.xmlvm.NotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[org.xmlvm.java.lang.String: void <init>()]
}

public void @this(org.xmlvm.Array<char> n1){
//XMLVM_BEGIN_WRAPPER[org.xmlvm.java.lang.String: void <init>(char[])]
    this.str = new global::System.String(n1.getCSharpArray());
//XMLVM_END_WRAPPER[org.xmlvm.java.lang.String: void <init>(char[])]
}

public override global::System.Object toString(){
//XMLVM_BEGIN_WRAPPER[org.xmlvm.java.lang.String: java.lang.String toString()]
	return this;
//XMLVM_END_WRAPPER[org.xmlvm.java.lang.String: java.lang.String toString()]
}

public virtual global::System.Object toCharArray(){
//XMLVM_BEGIN_WRAPPER[org.xmlvm.java.lang.String: char[] toCharArray()]
    return new org.xmlvm.Array<char>(this.str.ToCharArray());    
//XMLVM_END_WRAPPER[org.xmlvm.java.lang.String: char[] toCharArray()]
}

public override bool equals(java.lang.Object n1){
//XMLVM_BEGIN_WRAPPER[org.xmlvm.java.lang.String: boolean equals(java.lang.Object)]
if (this==n1) return true;
if (n1==null) return false;

java.lang.String _other = null;
try {
    _other = (java.lang.String) n1;
} catch(global::System.Exception) {
    return false;
} 

if (this.str.Equals(_other.str)) {
    return true;
} else {
    return false;
}

//XMLVM_END_WRAPPER[org.xmlvm.java.lang.String: boolean equals(java.lang.Object)]
}

public static global::System.Object valueOf(int n1){
//XMLVM_BEGIN_WRAPPER[org.xmlvm.java.lang.String: java.lang.String valueOf(int)]
java.lang.String _tmpStr = new java.lang.String();
_tmpStr.@this(new org.xmlvm.Array<char>(global::System.Convert.ToString(n1).ToCharArray()));
return _tmpStr;
//XMLVM_END_WRAPPER[org.xmlvm.java.lang.String: java.lang.String valueOf(int)]
}

public static global::System.Object valueOf(float n1){
//XMLVM_BEGIN_WRAPPER[org.xmlvm.java.lang.String: java.lang.String valueOf(float)]
java.lang.String _tmpStr = new java.lang.String();
_tmpStr.@this(new org.xmlvm.Array<char>(global::System.Convert.ToString(n1).ToCharArray()));
return _tmpStr;
//XMLVM_END_WRAPPER[org.xmlvm.java.lang.String: java.lang.String valueOf(float)]
}

public static global::System.Object valueOf(long n1){
//XMLVM_BEGIN_WRAPPER[org.xmlvm.java.lang.String: java.lang.String valueOf(long)]
java.lang.String _tmpStr = new java.lang.String();
_tmpStr.@this(new org.xmlvm.Array<char>(global::System.Convert.ToString(n1).ToCharArray()));
return _tmpStr;
//XMLVM_END_WRAPPER[org.xmlvm.java.lang.String: java.lang.String valueOf(long)]
}

public static global::System.Object valueOf(double n1){
//XMLVM_BEGIN_WRAPPER[org.xmlvm.java.lang.String: java.lang.String valueOf(double)]
java.lang.String _tmpStr = new java.lang.String();
_tmpStr.@this(new org.xmlvm.Array<char>(global::System.Convert.ToString(n1).ToCharArray()));
return _tmpStr;
//XMLVM_END_WRAPPER[org.xmlvm.java.lang.String: java.lang.String valueOf(double)]
}

//XMLVM_BEGIN_WRAPPER[org.xmlvm.java.lang.String]
	private global::System.String str;
	
	public String() {
	    this.str = "";
	}
/*
	public String(global::System.String str) {
		this.str = str;
	}

	public override global::System.String ToString() {
		return this.str;
	}
*/
//XMLVM_END_WRAPPER[org.xmlvm.java.lang.String]

} // end of class: String

} // end of namespace: org.xmlvm.java.lang
