
// Automatically generated by xmlvm2csharp. Do not edit!

using org.xmlvm;
using java = org.xmlvm.java;
namespace org.xmlvm.java.lang {
public class System: org.xmlvm.java.lang.Object {

static System() {
    @static();
}

public static org.xmlvm.java.io.PrintStream @out;

public new void @this(){
//XMLVM_BEGIN_WRAPPER[org.xmlvm.java.lang.System: void <init>()]
//XMLVM_END_WRAPPER[org.xmlvm.java.lang.System: void <init>()]
}

public static void arraycopy(org.xmlvm.java.lang.Object n1, int n2, org.xmlvm.java.lang.Object n3, int n4, int n5){
//XMLVM_BEGIN_WRAPPER[org.xmlvm.java.lang.System: void arraycopy(org.xmlvm.java.lang.Object, int, org.xmlvm.java.lang.Object, int, int)]
        // global::System.Array.Copy(n1, n2, n3, n4, n5);
	throw new NotYetImplementedException();
//XMLVM_END_WRAPPER[org.xmlvm.java.lang.System: void arraycopy(org.xmlvm.java.lang.Object, int, org.xmlvm.java.lang.Object, int, int)]
}

public static new void @static(){
//XMLVM_BEGIN_WRAPPER[org.xmlvm.java.lang.System: void <clinit>()]
	@out = new SystemPrintStream();
//XMLVM_END_WRAPPER[org.xmlvm.java.lang.System: void <clinit>()]
}

//XMLVM_BEGIN_WRAPPER[org.xmlvm.java.lang.System]
	private class SystemPrintStream : java.io.PrintStream{
		public override void println(java.lang.String str) {
			global::System.Console.WriteLine(str.ToString());
		}
	}

//XMLVM_END_WRAPPER[org.xmlvm.java.lang.System]

} // end of class: System

} // end of namespace: org.xmlvm.java.lang
