
// Automatically generated by xmlvm2csharp. Do not edit!

using org.xmlvm;
using java = org.xmlvm.java;
namespace org.xmlvm.java.lang {
public class Class: org.xmlvm.java.lang.Object {
public new void @this(){
//XMLVM_BEGIN_WRAPPER[org.xmlvm.java.lang.Class: void <init>()]
//XMLVM_END_WRAPPER[org.xmlvm.java.lang.Class: void <init>()]
}

//XMLVM_BEGIN_WRAPPER[org.xmlvm.java.lang.Class]
//XMLVM_END_WRAPPER[org.xmlvm.java.lang.Class]

} // end of class: Class

} // end of namespace: org.xmlvm.java.lang
