// Automatically generated by xmlvm2csharp (Do not edit).

using org.xmlvm;
using java = org.xmlvm.java;
namespace org.xmlvm.java.lang {
public class Class: org.xmlvm.java.lang.Object {
public new void @this(){
//XMLVM_BEGIN_WRAPPER[org.xmlvm.java.lang.Class: void <init>()]
//XMLVM_END_WRAPPER[org.xmlvm.java.lang.Class: void <init>()]
}

public virtual global::System.Object getName(){
//XMLVM_BEGIN_WRAPPER[org.xmlvm.java.lang.Class: org.xmlvm.java.lang.String getName()]
throw new org.xmlvm._nNotYetImplementedException();
//XMLVM_END_WRAPPER[org.xmlvm.java.lang.Class: org.xmlvm.java.lang.String getName()]
}

public static global::System.Object forName(org.xmlvm.java.lang.String n1){
//XMLVM_BEGIN_WRAPPER[org.xmlvm.java.lang.Class: org.xmlvm.java.lang.Class forName(org.xmlvm.java.lang.String)]
      throw new org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[org.xmlvm.java.lang.Class: org.xmlvm.java.lang.Class forName(org.xmlvm.java.lang.String)]
}

//XMLVM_BEGIN_WRAPPER[org.xmlvm.java.lang.Class]
//XMLVM_END_WRAPPER[org.xmlvm.java.lang.Class]

} // end of class: Class

} // end of namespace: org.xmlvm.java.lang
