
// Automatically generated by xmlvm2csharp. Do not edit!

using org.xmlvm;
using java = org.xmlvm.java;
namespace org.xmlvm.java.lang {
public class Exception: org.xmlvm.java.lang.Throwable {
public new void @this(){
//XMLVM_BEGIN_WRAPPER[org.xmlvm.java.lang.Exception: void <init>()]
base.@this();
//XMLVM_END_WRAPPER[org.xmlvm.java.lang.Exception: void <init>()]
}

public new void @this(java.lang.String n1){
//XMLVM_BEGIN_WRAPPER[org.xmlvm.java.lang.Exception: void <init>(java.lang.String)]
base.@this(n1);
//XMLVM_END_WRAPPER[org.xmlvm.java.lang.Exception: void <init>(java.lang.String)]
}

public new void @this(java.lang.String n1, java.lang.Throwable n2){
//XMLVM_BEGIN_WRAPPER[org.xmlvm.java.lang.Exception: void <init>(java.lang.String, java.lang.Throwable)]
base.@this(n1,n2);
//XMLVM_END_WRAPPER[org.xmlvm.java.lang.Exception: void <init>(java.lang.String, java.lang.Throwable)]
}

public new void @this(java.lang.Throwable n1){
//XMLVM_BEGIN_WRAPPER[org.xmlvm.java.lang.Exception: void <init>(java.lang.Throwable)]
base.@this(n1);
//XMLVM_END_WRAPPER[org.xmlvm.java.lang.Exception: void <init>(java.lang.Throwable)]
}

//XMLVM_BEGIN_WRAPPER[org.xmlvm.java.lang.Exception]
//XMLVM_END_WRAPPER[org.xmlvm.java.lang.Exception]

} // end of class: Exception

} // end of namespace: org.xmlvm.java.lang
