
// Automatically generated by xmlvm2csharp. Do not edit!

using org.xmlvm;
using java = org.xmlvm.java;
namespace org.xmlvm.java.lang {
public class StringBuilder: org.xmlvm.java.lang.Object {
public new void @this(){
//XMLVM_BEGIN_WRAPPER[org.xmlvm.java.lang.StringBuilder: void <init>()]
this.sb = new global::System.Text.StringBuilder();
//XMLVM_END_WRAPPER[org.xmlvm.java.lang.StringBuilder: void <init>()]
}

public void @this(java.lang.String n1){
//XMLVM_BEGIN_WRAPPER[org.xmlvm.java.lang.StringBuilder: void <init>(java.lang.String)]
this.sb = new global::System.Text.StringBuilder(n1.ToString());
//XMLVM_END_WRAPPER[org.xmlvm.java.lang.StringBuilder: void <init>(java.lang.String)]
}

public override java.lang.String toString(){
//XMLVM_BEGIN_WRAPPER[org.xmlvm.java.lang.StringBuilder: java.lang.String toString()]
return new java.lang.String(this.sb.ToString());
//XMLVM_END_WRAPPER[org.xmlvm.java.lang.StringBuilder: java.lang.String toString()]
}

public virtual java.lang.StringBuilder append(java.lang.String n1){
//XMLVM_BEGIN_WRAPPER[org.xmlvm.java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)]
this.sb.Append(n1.ToString());
return this;
//XMLVM_END_WRAPPER[org.xmlvm.java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)]
}

public virtual java.lang.StringBuilder append(int n1){
//XMLVM_BEGIN_WRAPPER[org.xmlvm.java.lang.StringBuilder: java.lang.StringBuilder append(int)]
this.sb.Append(n1);
return this;
//XMLVM_END_WRAPPER[org.xmlvm.java.lang.StringBuilder: java.lang.StringBuilder append(int)]
}

//XMLVM_BEGIN_WRAPPER[org.xmlvm.java.lang.StringBuilder]
private global::System.Text.StringBuilder sb;
//XMLVM_END_WRAPPER[org.xmlvm.java.lang.StringBuilder]

} // end of class: StringBuilder

} // end of namespace: org.xmlvm.java.lang
