// Automatically generated by xmlvm2csharp (Do not edit).

using org.xmlvm;
using java = org.xmlvm.java;
namespace org.xmlvm.java.lang {
public class StringBuilder: org.xmlvm.java.lang.Object {
public new void @this(){
//XMLVM_BEGIN_WRAPPER[org.xmlvm.java.lang.StringBuilder: void <init>()]
this.sb = new global::System.Text.StringBuilder();
//XMLVM_END_WRAPPER[org.xmlvm.java.lang.StringBuilder: void <init>()]
}

public void @this(java.lang.String n1){
//XMLVM_BEGIN_WRAPPER[org.xmlvm.java.lang.StringBuilder: void <init>(java.lang.String)]
this.sb = new global::System.Text.StringBuilder();
this.append((org.xmlvm._nArrayAdapter<char>)n1.toCharArray());
//XMLVM_END_WRAPPER[org.xmlvm.java.lang.StringBuilder: void <init>(java.lang.String)]
}

public override global::System.Object toString(){
//XMLVM_BEGIN_WRAPPER[org.xmlvm.java.lang.StringBuilder: java.lang.String toString()]
java.lang.String _tmpStr = new java.lang.String();
_tmpStr.@this(new org.xmlvm._nArrayAdapter<char>(this.sb.ToString().ToCharArray()));
return _tmpStr;
//XMLVM_END_WRAPPER[org.xmlvm.java.lang.StringBuilder: java.lang.String toString()]
}

public virtual global::System.Object append(java.lang.String n1){
//XMLVM_BEGIN_WRAPPER[org.xmlvm.java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)]
this.sb.Append(((org.xmlvm._nArrayAdapter<char>)n1.toCharArray()).getCSharpArray());
return this;
//XMLVM_END_WRAPPER[org.xmlvm.java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)]
}

public virtual global::System.Object append(org.xmlvm._nArrayAdapter<char> n1){
//XMLVM_BEGIN_WRAPPER[org.xmlvm.java.lang.StringBuilder: java.lang.StringBuilder append(char[])]
this.sb.Append(n1.getCSharpArray());
return this;
//XMLVM_END_WRAPPER[org.xmlvm.java.lang.StringBuilder: java.lang.StringBuilder append(char[])]
}

public virtual global::System.Object append(int n1){
//XMLVM_BEGIN_WRAPPER[org.xmlvm.java.lang.StringBuilder: java.lang.StringBuilder append(int)]
this.sb.Append(n1);
return this;
//XMLVM_END_WRAPPER[org.xmlvm.java.lang.StringBuilder: java.lang.StringBuilder append(int)]
}

//XMLVM_BEGIN_WRAPPER[org.xmlvm.java.lang.StringBuilder]
private global::System.Text.StringBuilder sb;
//XMLVM_END_WRAPPER[org.xmlvm.java.lang.StringBuilder]

} // end of class: StringBuilder

} // end of namespace: org.xmlvm.java.lang
