
// Automatically generated by xmlvm2csharp. Do not edit!

using org.xmlvm;
using java = org.xmlvm.java;
namespace org.xmlvm.java.lang {
public class Throwable: org.xmlvm.java.lang.Object {
public new void @this(){
//XMLVM_BEGIN_WRAPPER[org.xmlvm.java.lang.Throwable: void <init>()]
_message = null;
_cause = null;
//XMLVM_END_WRAPPER[org.xmlvm.java.lang.Throwable: void <init>()]
}

public void @this(java.lang.String n1){
//XMLVM_BEGIN_WRAPPER[org.xmlvm.java.lang.Throwable: void <init>(java.lang.String)]
_message = n1;
_cause = null;
//XMLVM_END_WRAPPER[org.xmlvm.java.lang.Throwable: void <init>(java.lang.String)]
}

public void @this(java.lang.String n1, java.lang.Throwable n2){
//XMLVM_BEGIN_WRAPPER[org.xmlvm.java.lang.Throwable: void <init>(java.lang.String, java.lang.Throwable)]
_message = n1;
_cause = n2;
//XMLVM_END_WRAPPER[org.xmlvm.java.lang.Throwable: void <init>(java.lang.String, java.lang.Throwable)]
}

public void @this(java.lang.Throwable n1){
//XMLVM_BEGIN_WRAPPER[org.xmlvm.java.lang.Throwable: void <init>(java.lang.Throwable)]
_message = null;
_cause = n1;
//XMLVM_END_WRAPPER[org.xmlvm.java.lang.Throwable: void <init>(java.lang.Throwable)]
}

public virtual java.lang.Throwable fillInStackTrace(){
//XMLVM_BEGIN_WRAPPER[org.xmlvm.java.lang.Throwable: java.lang.Throwable fillInStackTrace()]
throw new NotYetImplementedException();
//XMLVM_END_WRAPPER[org.xmlvm.java.lang.Throwable: java.lang.Throwable fillInStackTrace()]
}

public virtual java.lang.Throwable getCause(){
//XMLVM_BEGIN_WRAPPER[org.xmlvm.java.lang.Throwable: java.lang.Throwable getCause()]
return _cause;
//XMLVM_END_WRAPPER[org.xmlvm.java.lang.Throwable: java.lang.Throwable getCause()]
}

public virtual java.lang.String getLocalizedMessage(){
//XMLVM_BEGIN_WRAPPER[org.xmlvm.java.lang.Throwable: java.lang.String getLocalizedMessage()]
return getMessage();
//XMLVM_END_WRAPPER[org.xmlvm.java.lang.Throwable: java.lang.String getLocalizedMessage()]
}

public virtual java.lang.String getMessage(){
//XMLVM_BEGIN_WRAPPER[org.xmlvm.java.lang.Throwable: java.lang.String getMessage()]
return _message;
//XMLVM_END_WRAPPER[org.xmlvm.java.lang.Throwable: java.lang.String getMessage()]
}

public virtual java.lang.Throwable initCause(java.lang.Throwable n1){
//XMLVM_BEGIN_WRAPPER[org.xmlvm.java.lang.Throwable: java.lang.Throwable initCause(java.lang.Throwable)]
if (n1 == this) {
    throw new global::System.ArgumentException("A Throwable cannot be its own cause.");
} else if (_cause!=null) {
    throw new global::System.InvalidOperationException("This Throwable has already initialized its cause."); 
} else {
    _cause = n1;
}
return this;
//XMLVM_END_WRAPPER[org.xmlvm.java.lang.Throwable: java.lang.Throwable initCause(java.lang.Throwable)]
}

public virtual void printStackTrace(){
//XMLVM_BEGIN_WRAPPER[org.xmlvm.java.lang.Throwable: void printStackTrace()]
throw new NotYetImplementedException();
//XMLVM_END_WRAPPER[org.xmlvm.java.lang.Throwable: void printStackTrace()]
}

public virtual void printStackTrace(java.io.PrintStream n1){
//XMLVM_BEGIN_WRAPPER[org.xmlvm.java.lang.Throwable: void printStackTrace(java.io.PrintStream)]
throw new NotYetImplementedException();
//XMLVM_END_WRAPPER[org.xmlvm.java.lang.Throwable: void printStackTrace(java.io.PrintStream)]
}

public virtual void setStackTrace(org.xmlvm.Array<global::System.Object> n1){
//XMLVM_BEGIN_WRAPPER[org.xmlvm.java.lang.Throwable: void setStackTrace(org.xmlvm.java.lang.StackTraceElement[])]
//_stackTrace = n1;
throw new NotYetImplementedException();
//XMLVM_END_WRAPPER[org.xmlvm.java.lang.Throwable: void setStackTrace(org.xmlvm.java.lang.StackTraceElement[])]
}

public virtual org.xmlvm.java.lang.StackTraceElement getStackTrace(){
//XMLVM_BEGIN_WRAPPER[org.xmlvm.java.lang.Throwable: org.xmlvm.java.lang.StackTraceElement getStackTrace()]
//return _stackTrace;
throw new NotYetImplementedException();
//XMLVM_END_WRAPPER[org.xmlvm.java.lang.Throwable: org.xmlvm.java.lang.StackTraceElement getStackTrace()]
}

public override java.lang.String toString(){
//XMLVM_BEGIN_WRAPPER[org.xmlvm.java.lang.Throwable: java.lang.String toString()]
throw new NotYetImplementedException();
//XMLVM_END_WRAPPER[org.xmlvm.java.lang.Throwable: java.lang.String toString()]
}

//XMLVM_BEGIN_WRAPPER[org.xmlvm.java.lang.Throwable]
private java.lang.String _message;
private java.lang.Throwable _cause;
//private Java.Lang.StackTraceElement[] _stackTrace;
//XMLVM_END_WRAPPER[org.xmlvm.java.lang.Throwable]

} // end of class: Throwable

} // end of namespace: org.xmlvm.java.lang
