#! /bin/bash

# usage example: 
# (run in base xmlvm dir)
# (assuming mono installed)

XMLVM=dist/xmlvm.jar
LIB_PATH=src/xmlvm2csharp/compat-lib/csharp
DUMMY_PATH=src/xmlvm2csharp/compat-lib/dummy
TEST_PATH=src/xmlvm2csharp/test
TEST=org/xmlvm/test/ControlStructureTest

ant 

# compile compat-lib:
javac -classpath $DUMMY_PATH $DUMMY_PATH/org/xmlvm/java/*/*.java
java -jar $XMLVM --in=$DUMMY_PATH --out=$LIB_PATH --target=gen-csharp-wrappers
gmcs -target:library -out:Xmlvm.dll $LIB_PATH/org/xmlvm/*.cs $LIB_PATH/org/xmlvm/java/*/*.cs

# compile test:
javac -classpath $TEST_PATH $TEST_PATH/$TEST.java
java -jar $XMLVM --in=$TEST_PATH/$TEST.class --out=$TEST_PATH --target=csharp
gmcs -out:ControlStructureTest.exe -target:exe -reference:Xmlvm.dll $TEST_PATH/$TEST.cs

# run
mono ControlStructureTest.exe