// Automatically generated by xmlvm2csharp (Do not edit).

using org.xmlvm;
using java = org.xmlvm.java;
namespace org.xmlvm.java.io {
public class FilterOutputStream: org.xmlvm.java.io.OutputStream {
public new void @this(){
//XMLVM_BEGIN_WRAPPER[org.xmlvm.java.io.FilterOutputStream: void <init>()]
//XMLVM_END_WRAPPER[org.xmlvm.java.io.FilterOutputStream: void <init>()]
}

//XMLVM_BEGIN_WRAPPER[org.xmlvm.java.io.FilterOutputStream]
//XMLVM_END_WRAPPER[org.xmlvm.java.io.FilterOutputStream]

} // end of class: FilterOutputStream

} // end of namespace: org.xmlvm.java.io
