// Automatically generated by xmlvm2csharp (Do not edit).

using org.xmlvm;
using java = org.xmlvm.java;
namespace org.xmlvm.java.io {
public class PrintStream: org.xmlvm.java.io.FilterOutputStream {
public new void @this(){
//XMLVM_BEGIN_WRAPPER[org.xmlvm.java.io.PrintStream: void <init>()]
//XMLVM_END_WRAPPER[org.xmlvm.java.io.PrintStream: void <init>()]
}

public virtual void println(java.lang.String n1){
//XMLVM_BEGIN_WRAPPER[org.xmlvm.java.io.PrintStream: void println(java.lang.String)]
//XMLVM_END_WRAPPER[org.xmlvm.java.io.PrintStream: void println(java.lang.String)]
}

public virtual void println(int n1){
//XMLVM_BEGIN_WRAPPER[org.xmlvm.java.io.PrintStream: void println(int)]
this.println((java.lang.String) java.lang.String.valueOf(n1));
//XMLVM_END_WRAPPER[org.xmlvm.java.io.PrintStream: void println(int)]
}

public virtual void println(float n1){
//XMLVM_BEGIN_WRAPPER[org.xmlvm.java.io.PrintStream: void println(float)]
this.println((java.lang.String) java.lang.String.valueOf(n1));
//XMLVM_END_WRAPPER[org.xmlvm.java.io.PrintStream: void println(float)]
}

public virtual void println(double n1){
//XMLVM_BEGIN_WRAPPER[org.xmlvm.java.io.PrintStream: void println(double)]
this.println((java.lang.String) java.lang.String.valueOf(n1));
//XMLVM_END_WRAPPER[org.xmlvm.java.io.PrintStream: void println(double)]
}

public virtual void println(long n1){
//XMLVM_BEGIN_WRAPPER[org.xmlvm.java.io.PrintStream: void println(long)]
this.println((java.lang.String) java.lang.String.valueOf(n1));
//XMLVM_END_WRAPPER[org.xmlvm.java.io.PrintStream: void println(long)]
}

//XMLVM_BEGIN_WRAPPER[org.xmlvm.java.io.PrintStream]
//XMLVM_END_WRAPPER[org.xmlvm.java.io.PrintStream]

} // end of class: PrintStream

} // end of namespace: org.xmlvm.java.io
