// Automatically generated by xmlvm2csharp (do not edit).

using org.xmlvm;
namespace org.xmlvm.runtime {
public class XMLVMOutputStream: java.io.OutputStream {
public static void nativeWrite(int n1){
//XMLVM_BEGIN_WRAPPER[org.xmlvm.runtime.XMLVMOutputStream: void nativeWrite(int)]
#if CONSOLE
    global::System.Console.Write((char) n1);
#else 
    throw new org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
#endif
//XMLVM_END_WRAPPER[org.xmlvm.runtime.XMLVMOutputStream: void nativeWrite(int)]
}

//XMLVM_BEGIN_WRAPPER[org.xmlvm.runtime.XMLVMOutputStream]
//XMLVM_END_WRAPPER[org.xmlvm.runtime.XMLVMOutputStream]

} // end of class: XMLVMOutputStream

} // end of namespace: org.xmlvm.runtime
