
// Automatically generated by xmlvm2csharp. Do not edit!

using org.xmlvm;
using java = org.xmlvm.java;
namespace org.xmlvm.java.io {
public class OutputStream: org.xmlvm.java.lang.Object {
public new void @this(){
//XMLVM_BEGIN_WRAPPER[org.xmlvm.java.io.OutputStream: void <init>()]
//XMLVM_END_WRAPPER[org.xmlvm.java.io.OutputStream: void <init>()]
}

//XMLVM_BEGIN_WRAPPER[org.xmlvm.java.io.OutputStream]
//XMLVM_END_WRAPPER[org.xmlvm.java.io.OutputStream]

} // end of class: OutputStream

} // end of namespace: org.xmlvm.java.io
