// Automatically generated by xmlvm2csharp. Do not edit!

using org.xmlvm;
using java = org.xmlvm.java;
namespace Compatlib.System {
public class Delegate: java.lang.Object {
public new void @this(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Delegate: void <init>()]
//XMLVM_END_WRAPPER[Compatlib.System.Delegate: void <init>()]
}

//XMLVM_BEGIN_WRAPPER[Compatlib.System.Delegate]
//XMLVM_END_WRAPPER[Compatlib.System.Delegate]

} // end of class: Delegate

} // end of namespace: Compatlib.System
