
// Automatically generated by xmlvm2csharp. Do not edit!

using org.xmlvm;
using java = org.xmlvm.java;
namespace Compatlib.System {
public class EventHandler: Compatlib.System.MulticastDelegate {
public void @this(Compatlib.System.Object n1, Compatlib.System.String n2){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.EventHandler: void <init>(Compatlib.System.Object, Compatlib.System.String)]
            this.owner = n1;
            this.method = n2;
//XMLVM_END_WRAPPER[Compatlib.System.EventHandler: void <init>(Compatlib.System.Object, Compatlib.System.String)]
}

public virtual void Invoke(Compatlib.System.Object n1, Compatlib.System.EventArgs n2){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.EventHandler: void Invoke(Compatlib.System.Object, Compatlib.System.EventArgs)]
//XMLVM_END_WRAPPER[Compatlib.System.EventHandler: void Invoke(Compatlib.System.Object, Compatlib.System.EventArgs)]
}

//XMLVM_BEGIN_WRAPPER[Compatlib.System.EventHandler]
        public global::System.Object owner;
        public Compatlib.System.String method;
//XMLVM_END_WRAPPER[Compatlib.System.EventHandler]

} // end of class: EventHandler

} // end of namespace: Compatlib.System
