
// Automatically generated by xmlvm2csharp. Do not edit!

using org.xmlvm;
using java = org.xmlvm.java;
namespace Compatlib.System {
public class EventArgs: Compatlib.System.Object {
public static Compatlib.System.EventArgs Empty;

public new void @this(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.EventArgs: void <init>()]
//XMLVM_END_WRAPPER[Compatlib.System.EventArgs: void <init>()]
}

//XMLVM_BEGIN_WRAPPER[Compatlib.System.EventArgs]
//XMLVM_END_WRAPPER[Compatlib.System.EventArgs]

} // end of class: EventArgs

} // end of namespace: Compatlib.System
