
// Automatically generated by xmlvm2csharp. Do not edit!

using org.xmlvm;
using java = org.xmlvm.java;
namespace Compatlib.System {
public interface IEquatable {
//XMLVM_BEGIN_WRAPPER[Compatlib.System.IEquatable]
//XMLVM_END_WRAPPER[Compatlib.System.IEquatable]

} // end of class: IEquatable

} // end of namespace: Compatlib.System
