
// Automatically generated by xmlvm2csharp. Do not edit!

using org.xmlvm;
using java = org.xmlvm.java;
namespace Compatlib.System {
public class String: Compatlib.System.Object {

static String() {
    @static();
}

public java.lang.String value;

public static Compatlib.System.String Empty;

public static new void @static(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.String: void <clinit>()]
//XMLVM_END_WRAPPER[Compatlib.System.String: void <clinit>()]
}

public void @this(java.lang.String n1){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.String: void <init>(java.lang.String)]
    this.value = n1;
//XMLVM_END_WRAPPER[Compatlib.System.String: void <init>(java.lang.String)]
}

public override Compatlib.System.String ToString(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.String: Compatlib.System.String ToString()]
    return this;
//XMLVM_END_WRAPPER[Compatlib.System.String: Compatlib.System.String ToString()]
}

public override java.lang.String toString(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.String: java.lang.String toString()]
    return this.value;
//XMLVM_END_WRAPPER[Compatlib.System.String: java.lang.String toString()]
}

//XMLVM_BEGIN_WRAPPER[Compatlib.System.String]
//XMLVM_END_WRAPPER[Compatlib.System.String]

} // end of class: String

} // end of namespace: Compatlib.System
