
// Automatically generated by xmlvm2csharp. Do not edit!

using org.xmlvm;
using java = org.xmlvm.java;
namespace Compatlib.System {
public class UriKind: java.lang.Object {

static UriKind() {
    @static();
}

public static Compatlib.System.UriKind RelativeOrAbsolute;

public static new void @static(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.UriKind: void <clinit>()]
    RelativeOrAbsolute = new UriKind();
    RelativeOrAbsolute.uriKind = global::System.UriKind.RelativeOrAbsolute;
//XMLVM_END_WRAPPER[Compatlib.System.UriKind: void <clinit>()]
}

public new void @this(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.UriKind: void <init>()]
//XMLVM_END_WRAPPER[Compatlib.System.UriKind: void <init>()]
}

//XMLVM_BEGIN_WRAPPER[Compatlib.System.UriKind]
public global::System.UriKind uriKind;
//XMLVM_END_WRAPPER[Compatlib.System.UriKind]

} // end of class: UriKind

} // end of namespace: Compatlib.System
