
// Automatically generated by xmlvm2csharp. Do not edit!

using org.xmlvm;
using java = org.xmlvm.java;
namespace Compatlib.System.Windows {
public class Freezable: Compatlib.System.Windows.DependencyObject {
public new void @this(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Freezable: void <init>()]
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Freezable: void <init>()]
}

//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Freezable]
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Freezable]

} // end of class: Freezable

} // end of namespace: Compatlib.System.Windows
