
// Automatically generated by xmlvm2csharp. Do not edit!

using org.xmlvm;
using java = org.xmlvm.java;
namespace Compatlib.System.Windows {
public class RoutedEventArgs: Compatlib.System.EventArgs {
public new void @this(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.RoutedEventArgs: void <init>()]
//XMLVM_END_WRAPPER[Compatlib.System.Windows.RoutedEventArgs: void <init>()]
}

//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.RoutedEventArgs]
public global::System.Windows.RoutedEventArgs args;
//XMLVM_END_WRAPPER[Compatlib.System.Windows.RoutedEventArgs]

} // end of class: RoutedEventArgs

} // end of namespace: Compatlib.System.Windows
