
// Automatically generated by xmlvm2csharp. Do not edit!

using org.xmlvm;
using java = org.xmlvm.java;
namespace Compatlib.System.Windows {
public class Size: Compatlib.System.Object {
public new void @this(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Size: void <init>()]
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Size: void <init>()]
}

public virtual double getWidth(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Size: double getWidth()]
    return size.Width;
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Size: double getWidth()]
}

public virtual double getHeight(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Size: double getHeight()]
    return size.Height;
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Size: double getHeight()]
}

//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Size]
public global::System.Windows.Size size;
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Size]

} // end of class: Size

} // end of namespace: Compatlib.System.Windows
