
// Automatically generated by xmlvm2csharp. Do not edit!

using org.xmlvm;
using java = org.xmlvm.java;
namespace Compatlib.System.Windows {
public class Application: Compatlib.System.Windows.Threading.DispatcherObject {
public Compatlib.System.Windows.StartUpEvent Startup;

public new void @this(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Application: void <init>()]
    this.Startup = new Compatlib.System.Windows.StartUpEvent();
    this.Startup.@this();

    app.Startup += StartUpHandler;
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Application: void <init>()]
}

public virtual Compatlib.System.Windows.UIElement getRootVisual(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Application: Compatlib.System.Windows.UIElement getRootVisual()]
    return rootVisual;
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Application: Compatlib.System.Windows.UIElement getRootVisual()]
}

public virtual void setRootVisual(Compatlib.System.Windows.UIElement n1){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Application: void setRootVisual(Compatlib.System.Windows.UIElement)]
    this.rootVisual = n1;
    app.RootVisual = n1.element;
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Application: void setRootVisual(Compatlib.System.Windows.UIElement)]
}

//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Application]
private Compatlib.System.Windows.UIElement rootVisual;
private global::System.Windows.Application app = Compatlib.System.Windows.ApplicationDelegate.Current;

public void StartUpHandler(object sender, global::System.Windows.StartupEventArgs args)
{
    Compatlib.System.Windows.StartupEventArgs newArgs = new Compatlib.System.Windows.StartupEventArgs();
    newArgs.args = args;
    this.Startup.__fire(this, newArgs);
}
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Application]

} // end of class: Application

} // end of namespace: Compatlib.System.Windows
