
// Automatically generated by xmlvm2csharp. Do not edit!

using org.xmlvm;
using java = org.xmlvm.java;
namespace Compatlib.System.Windows {
public class DependencyObject: Compatlib.System.Windows.Threading.DispatcherObject {
public new void @this(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.DependencyObject: void <init>()]
//XMLVM_END_WRAPPER[Compatlib.System.Windows.DependencyObject: void <init>()]
}

//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.DependencyObject]
//XMLVM_END_WRAPPER[Compatlib.System.Windows.DependencyObject]

} // end of class: DependencyObject

} // end of namespace: Compatlib.System.Windows
