
// Automatically generated by xmlvm2csharp. Do not edit!

using org.xmlvm;
using java = org.xmlvm.java;
namespace Compatlib.System.Windows {
public class FrameworkElement: Compatlib.System.Windows.UIElement {
public new void @this(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.FrameworkElement: void <init>()]
//XMLVM_END_WRAPPER[Compatlib.System.Windows.FrameworkElement: void <init>()]
}

public virtual Compatlib.System.Windows.Size ArrangeOverride(Compatlib.System.Windows.Size n1){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.FrameworkElement: Compatlib.System.Windows.Size ArrangeOverride(Compatlib.System.Windows.Size)]
    return null;
//XMLVM_END_WRAPPER[Compatlib.System.Windows.FrameworkElement: Compatlib.System.Windows.Size ArrangeOverride(Compatlib.System.Windows.Size)]
}

public virtual Compatlib.System.Windows.Size MeasureOverride(Compatlib.System.Windows.Size n1){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.FrameworkElement: Compatlib.System.Windows.Size MeasureOverride(Compatlib.System.Windows.Size)]
    return null;
//XMLVM_END_WRAPPER[Compatlib.System.Windows.FrameworkElement: Compatlib.System.Windows.Size MeasureOverride(Compatlib.System.Windows.Size)]
}

//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.FrameworkElement]
//XMLVM_END_WRAPPER[Compatlib.System.Windows.FrameworkElement]

} // end of class: FrameworkElement

} // end of namespace: Compatlib.System.Windows
