// Automatically generated by xmlvm2csharp. Do not edit!

using org.xmlvm;
using java = org.xmlvm.java;
namespace Compatlib.System.Windows {
public class FrameworkElement: Compatlib.System.Windows.UIElement {
public new void @this(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.FrameworkElement: void <init>()]
//XMLVM_END_WRAPPER[Compatlib.System.Windows.FrameworkElement: void <init>()]
}

public virtual global::System.Object ArrangeOverride(Compatlib.System.Windows.Size n1){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.FrameworkElement: Compatlib.System.Windows.Size ArrangeOverride(Compatlib.System.Windows.Size)]
    return null;
//XMLVM_END_WRAPPER[Compatlib.System.Windows.FrameworkElement: Compatlib.System.Windows.Size ArrangeOverride(Compatlib.System.Windows.Size)]
}

public virtual global::System.Object MeasureOverride(Compatlib.System.Windows.Size n1){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.FrameworkElement: Compatlib.System.Windows.Size MeasureOverride(Compatlib.System.Windows.Size)]
    return null;
//XMLVM_END_WRAPPER[Compatlib.System.Windows.FrameworkElement: Compatlib.System.Windows.Size MeasureOverride(Compatlib.System.Windows.Size)]
}

public virtual void setWidth(double n1){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.FrameworkElement: void setWidth(double)]
    ((global::System.Windows.FrameworkElement)base.element).Width = n1;
//XMLVM_END_WRAPPER[Compatlib.System.Windows.FrameworkElement: void setWidth(double)]
}

public virtual void setHeight(double n1){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.FrameworkElement: void setHeight(double)]
    ((global::System.Windows.FrameworkElement)base.element).Height = n1;
//XMLVM_END_WRAPPER[Compatlib.System.Windows.FrameworkElement: void setHeight(double)]
}

public virtual global::System.Object getName(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.FrameworkElement: Compatlib.System.String getName()]
    Compatlib.System.String ret = new Compatlib.System.String();
    ret.@this(org.xmlvm.Util.toJavaString(((global::System.Windows.FrameworkElement)base.element).Name));
    return ret;
//XMLVM_END_WRAPPER[Compatlib.System.Windows.FrameworkElement: Compatlib.System.String getName()]
}

public virtual void setName(Compatlib.System.String n1){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.FrameworkElement: void setName(Compatlib.System.String)]
    ((global::System.Windows.FrameworkElement)base.element).Name = org.xmlvm.Util.toNativeString((java.lang.String)n1.toString());
//XMLVM_END_WRAPPER[Compatlib.System.Windows.FrameworkElement: void setName(Compatlib.System.String)]
}

public virtual void setHorizontalAlignment(Compatlib.System.Windows.HorizontalAlignment n1){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.FrameworkElement: void setHorizontalAlignment(Compatlib.System.Windows.HorizontalAlignment)]
    ((global::System.Windows.FrameworkElement)base.element).HorizontalAlignment = n1.horizontalAlignment;
//XMLVM_END_WRAPPER[Compatlib.System.Windows.FrameworkElement: void setHorizontalAlignment(Compatlib.System.Windows.HorizontalAlignment)]
}

public virtual void setMinWidth(int n1){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.FrameworkElement: void setMinWidth(int)]
    ((global::System.Windows.FrameworkElement)base.element).MinWidth = n1;
//XMLVM_END_WRAPPER[Compatlib.System.Windows.FrameworkElement: void setMinWidth(int)]
}

public virtual void setMargin(Compatlib.System.Windows.Thickness n1){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.FrameworkElement: void setMargin(Compatlib.System.Windows.Thickness)]
    ((global::System.Windows.FrameworkElement)base.element).Margin = n1.thickness;
//XMLVM_END_WRAPPER[Compatlib.System.Windows.FrameworkElement: void setMargin(Compatlib.System.Windows.Thickness)]
}

//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.FrameworkElement]
//XMLVM_END_WRAPPER[Compatlib.System.Windows.FrameworkElement]

} // end of class: FrameworkElement

} // end of namespace: Compatlib.System.Windows
