
// Automatically generated by xmlvm2csharp. Do not edit!

using org.xmlvm;
using java = org.xmlvm.java;
namespace Compatlib.System.Windows {
public class Rect: Compatlib.System.Object,Compatlib.System.IFormattable {
public void @this(float n1, float n2, int n3, int n4){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Rect: void <init>(float, float, int, int)]
    rect = new global::System.Windows.Rect(n1, n2, n3, n4);
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Rect: void <init>(float, float, int, int)]
}

//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Rect]
public global::System.Windows.Rect rect;
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Rect]

} // end of class: Rect

} // end of namespace: Compatlib.System.Windows
