// Automatically generated by xmlvm2csharp (do not edit).

using global::org.xmlvm;
using global::java = global::org.xmlvm.java;
namespace Compatlib.System.Windows {
public class Vector: global::java.lang.Object {
private double _fX;

private double _fY;

public new void @this(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Vector: void <init>()]
    global::org.xmlvm._nElement _r0;
    _r0.i = 0;
    _r0.l = 0;
    _r0.f = 0;
    _r0.d = 0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r0_o = this;
    ((global::java.lang.Object) _r0_o).@this();
    return;
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Vector: void <init>()]
}

public virtual double getX(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Vector: double getX()]
    global::org.xmlvm._nElement _r0;
    _r0.i = 0;
    _r0.l = 0;
    _r0.f = 0;
    _r0.d = 0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    _r1.i = 0;
    _r1.l = 0;
    _r1.f = 0;
    _r1.d = 0;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nElement _r2;
    _r2.i = 0;
    _r2.l = 0;
    _r2.f = 0;
    _r2.d = 0;
    global::System.Object _r2_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r2_o = this;
    _r0.d = ((global::Compatlib.System.Windows.Vector) _r2_o)._fX;
    return _r0.d;
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Vector: double getX()]
}

public virtual void setX(double n1){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Vector: void setX(double)]
    global::org.xmlvm._nElement _r0;
    _r0.i = 0;
    _r0.l = 0;
    _r0.f = 0;
    _r0.d = 0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    _r1.i = 0;
    _r1.l = 0;
    _r1.f = 0;
    _r1.d = 0;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nElement _r2;
    _r2.i = 0;
    _r2.l = 0;
    _r2.f = 0;
    _r2.d = 0;
    global::System.Object _r2_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r0_o = this;
    _r1.d = n1;
    ((global::Compatlib.System.Windows.Vector) _r0_o)._fX = _r1.d;
    return;
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Vector: void setX(double)]
}

public virtual double getY(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Vector: double getY()]
    global::org.xmlvm._nElement _r0;
    _r0.i = 0;
    _r0.l = 0;
    _r0.f = 0;
    _r0.d = 0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    _r1.i = 0;
    _r1.l = 0;
    _r1.f = 0;
    _r1.d = 0;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nElement _r2;
    _r2.i = 0;
    _r2.l = 0;
    _r2.f = 0;
    _r2.d = 0;
    global::System.Object _r2_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r2_o = this;
    _r0.d = ((global::Compatlib.System.Windows.Vector) _r2_o)._fY;
    return _r0.d;
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Vector: double getY()]
}

public virtual void setY(double n1){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Vector: void setY(double)]
    global::org.xmlvm._nElement _r0;
    _r0.i = 0;
    _r0.l = 0;
    _r0.f = 0;
    _r0.d = 0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    _r1.i = 0;
    _r1.l = 0;
    _r1.f = 0;
    _r1.d = 0;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nElement _r2;
    _r2.i = 0;
    _r2.l = 0;
    _r2.f = 0;
    _r2.d = 0;
    global::System.Object _r2_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r0_o = this;
    _r1.d = n1;
    ((global::Compatlib.System.Windows.Vector) _r0_o)._fY = _r1.d;
    return;
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Vector: void setY(double)]
}

//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Vector]
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Vector]

} // end of class: Vector

} // end of namespace: Compatlib.System.Windows
