
// Automatically generated by xmlvm2csharp. Do not edit!

using org.xmlvm;
using java = org.xmlvm.java;
namespace Compatlib.System.Windows.Media {
public class Colors: Compatlib.System.Object {

static Colors() {
    @static();
}

public static Compatlib.System.Windows.Media.Color White;

public static Compatlib.System.Windows.Media.Color Blue;

public static new void @static(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Media.Colors: void <clinit>()]
    White = Color.FromRgb(0xFF, 0xFF, 0xFF);
    Blue = Color.FromRgb(0x00, 0x00, 0xFF);
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Media.Colors: void <clinit>()]
}

public new void @this(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Media.Colors: void <init>()]
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Media.Colors: void <init>()]
}

//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Media.Colors]
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Media.Colors]

} // end of class: Colors

} // end of namespace: Compatlib.System.Windows.Media
