// Automatically generated by xmlvm2csharp. Do not edit!

using org.xmlvm;
using java = org.xmlvm.java;
namespace Compatlib.System.Windows.Media {
public abstract class TileBrush: Compatlib.System.Windows.Media.Brush {
public new void @this(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Media.TileBrush: void <init>()]
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Media.TileBrush: void <init>()]
}

//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Media.TileBrush]
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Media.TileBrush]

} // end of class: TileBrush

} // end of namespace: Compatlib.System.Windows.Media
