
// Automatically generated by xmlvm2csharp. Do not edit!

using org.xmlvm;
using java = org.xmlvm.java;
namespace Compatlib.System.Windows.Controls {
public class Control: Compatlib.System.Windows.FrameworkElement {
public new void @this(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Controls.Control: void <init>()]
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Controls.Control: void <init>()]
}

//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Controls.Control]
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Controls.Control]

} // end of class: Control

} // end of namespace: Compatlib.System.Windows.Controls
