
// Automatically generated by xmlvm2csharp. Do not edit!

using org.xmlvm;
using java = org.xmlvm.java;
namespace Compatlib.System.Windows.Controls {
public class PresentationFrameworkCollection: Compatlib.System.Windows.DependencyObject {
public new void @this(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Controls.PresentationFrameworkCollection: void <init>()]
    elements = new global::System.Collections.Generic.List<java.lang.Object>();
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Controls.PresentationFrameworkCollection: void <init>()]
}

public virtual void Add(java.lang.Object n1){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Controls.PresentationFrameworkCollection: void Add(java.lang.Object)]
elements.Add(n1);
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Controls.PresentationFrameworkCollection: void Add(java.lang.Object)]
}

public virtual Compatlib.System.Collections.Generics.IEnumerator GetEnumerator(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Controls.PresentationFrameworkCollection: Compatlib.System.Collections.Generics.IEnumerator GetEnumerator()]
    return new Enumerator(elements);
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Controls.PresentationFrameworkCollection: Compatlib.System.Collections.Generics.IEnumerator GetEnumerator()]
}

public static java.util.List access_20(Compatlib.System.Windows.Controls.PresentationFrameworkCollection n1){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Controls.PresentationFrameworkCollection: java.util.List access$0(Compatlib.System.Windows.Controls.PresentationFrameworkCollection)]
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Controls.PresentationFrameworkCollection: java.util.List access$0(Compatlib.System.Windows.Controls.PresentationFrameworkCollection)]
}

//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Controls.PresentationFrameworkCollection]
private global::System.Collections.Generic.List<java.lang.Object> elements;

private class Enumerator : Compatlib.System.Collections.Generics.IEnumerator
{
    private int index;
    private global::System.Collections.Generic.List<java.lang.Object> elements;

    public java.lang.Object getCurrent()
    {
        return this.elements[index];
    }

    public int MoveNext()
    {
        index++;
        return index < elements.Count ? 1 : 0;
    }

    public Enumerator(global::System.Collections.Generic.List<java.lang.Object> elements)
    {
        this.elements = elements;
    }
}
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Controls.PresentationFrameworkCollection]

} // end of class: PresentationFrameworkCollection

} // end of namespace: Compatlib.System.Windows.Controls
