
// Automatically generated by xmlvm2csharp. Do not edit!

using org.xmlvm;
using java = org.xmlvm.java;
namespace Compatlib.System.Windows.Controls {
public class PresentationFrameworkCollection_2PresentationFrameworkCollectionEnumerator: java.lang.Object,Compatlib.System.Collections.Generics.IEnumerator {
public Compatlib.System.Windows.Controls.PresentationFrameworkCollection this_20;

public virtual java.lang.Object getCurrent(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Controls.PresentationFrameworkCollection$PresentationFrameworkCollectionEnumerator: java.lang.Object getCurrent()]
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Controls.PresentationFrameworkCollection$PresentationFrameworkCollectionEnumerator: java.lang.Object getCurrent()]
}

public virtual int MoveNext(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Controls.PresentationFrameworkCollection$PresentationFrameworkCollectionEnumerator: boolean MoveNext()]
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Controls.PresentationFrameworkCollection$PresentationFrameworkCollectionEnumerator: boolean MoveNext()]
}

public void @this(Compatlib.System.Windows.Controls.PresentationFrameworkCollection n1, Compatlib.System.Windows.Controls.PresentationFrameworkCollection_2PresentationFrameworkCollectionEnumerator n2){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Controls.PresentationFrameworkCollection$PresentationFrameworkCollectionEnumerator: void <init>(Compatlib.System.Windows.Controls.PresentationFrameworkCollection, Compatlib.System.Windows.Controls.PresentationFrameworkCollection$PresentationFrameworkCollectionEnumerator)]
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Controls.PresentationFrameworkCollection$PresentationFrameworkCollectionEnumerator: void <init>(Compatlib.System.Windows.Controls.PresentationFrameworkCollection, Compatlib.System.Windows.Controls.PresentationFrameworkCollection$PresentationFrameworkCollectionEnumerator)]
}

//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Controls.PresentationFrameworkCollection$PresentationFrameworkCollectionEnumerator]
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Controls.PresentationFrameworkCollection$PresentationFrameworkCollectionEnumerator]

} // end of class: PresentationFrameworkCollection_2PresentationFrameworkCollectionEnumerator

} // end of namespace: Compatlib.System.Windows.Controls
