// Automatically generated by xmlvm2csharp. Do not edit!

using org.xmlvm;
using java = org.xmlvm.java;
namespace Compatlib.System.Windows.Controls {
public class PresentationFrameworkCollection_2PresentationFrameworkCollectionEnumerator: java.lang.Object,Compatlib.System.Collections.Generics.IEnumerator {
public Compatlib.System.Windows.Controls.PresentationFrameworkCollection _fthis_20;

public virtual java.lang.Object getCurrent(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Controls.PresentationFrameworkCollection$PresentationFrameworkCollectionEnumerator: java.lang.Object getCurrent()]
return null;
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Controls.PresentationFrameworkCollection$PresentationFrameworkCollectionEnumerator: java.lang.Object getCurrent()]
}

public virtual bool MoveNext(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Controls.PresentationFrameworkCollection$PresentationFrameworkCollectionEnumerator: boolean MoveNext()]
return false;
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Controls.PresentationFrameworkCollection$PresentationFrameworkCollectionEnumerator: boolean MoveNext()]
}

//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Controls.PresentationFrameworkCollection$PresentationFrameworkCollectionEnumerator]
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Controls.PresentationFrameworkCollection$PresentationFrameworkCollectionEnumerator]

} // end of class: PresentationFrameworkCollection_2PresentationFrameworkCollectionEnumerator

} // end of namespace: Compatlib.System.Windows.Controls
