// Automatically generated by xmlvm2csharp. Do not edit!

using org.xmlvm;

namespace Compatlib.System.Windows.Controls.Primitives {
public class Popup: global::Compatlib.System.Windows.FrameworkElement {
public new void @this(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Controls.Primitives.Popup: void <init>()]
    base.element = new global::System.Windows.Controls.Primitives.Popup();
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Controls.Primitives.Popup: void <init>()]
}

public virtual void setIsOpen(bool n1){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Controls.Primitives.Popup: void setIsOpen(boolean)]
    ((global::System.Windows.Controls.Primitives.Popup)base.element).IsOpen = n1;
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Controls.Primitives.Popup: void setIsOpen(boolean)]
}

public virtual void setChild(Compatlib.System.Windows.UIElement n1){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Controls.Primitives.Popup: void setChild(Compatlib.System.Windows.UIElement)]
    ((global::System.Windows.Controls.Primitives.Popup)base.element).Child = n1.element;
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Controls.Primitives.Popup: void setChild(Compatlib.System.Windows.UIElement)]
}

//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Controls.Primitives.Popup]
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Controls.Primitives.Popup]

} // end of class: Popup

} // end of namespace: Compatlib.System.Windows.Controls.Primitives
