// Automatically generated by xmlvm2csharp. Do not edit!

using org.xmlvm;
using java = org.xmlvm.java;
namespace Compatlib.System.Windows.Media {
public class Visual: Compatlib.System.Windows.DependencyObject {
public new void @this(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Media.Visual: void <init>()]
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Media.Visual: void <init>()]
}

//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Media.Visual]
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Media.Visual]

} // end of class: Visual

} // end of namespace: Compatlib.System.Windows.Media
