// Automatically generated by xmlvm2csharp. Do not edit!

using org.xmlvm;
using java = org.xmlvm.java;
namespace Compatlib.System.Windows.Media.Imaging {
public class BitmapSource: Compatlib.System.Windows.Media.ImageSource {
public new void @this(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Media.Imaging.BitmapSource: void <init>()]
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Media.Imaging.BitmapSource: void <init>()]
}

//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Media.Imaging.BitmapSource]
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Media.Imaging.BitmapSource]

} // end of class: BitmapSource

} // end of namespace: Compatlib.System.Windows.Media.Imaging
